### ISSUE TITLE
Emit single event on Multi-Order request

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#101]
Currently, the `placeMultiSellOrder` in _SnappAuction.sol_ makes use of `placeSellOrder` which emits an individual event for each order placed. It would be significantly more gas efficient (see discussion on #100) to emit a single event with arrays of orders information. This, however, would also require adaptation to how the event listener (as part of [dex-services](https://github.com/gnosis/dex-services) repo) handles this information. Specifically, [here](https://github.com/gnosis/dex-services/blob/ab0c607f5170581f9e29881eab34c05361c5c128/event_listener/dfusion_db/snapp_event_receiver.py#L145-L154)

**Comment by fleupold** [comment]
I think there is a stronger argument here to reuse the existing event, since the entire code path inside the listener can be reused and there is less events that are basically meaning the same things. 
For standing orders that was not the case (we needed a new event anyways) and therefore it is more straightforward to emit all orders in a single event.

**Comment by bh2smith** [comment]
So as I understand @fleupold, you are in favour of having individual events regular orders but single events for Standing orders from reserved accounts?
