### ISSUE TITLE
[Question] Unreserved Order Batch Updates

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#109]
In placeStandingSellOrder we have unreserved order batch updates checked for and given as

https://github.com/gnosis/dex-contracts/blob/18b76664f0de6572a7998b1f06ea9537f6d2489b/contracts/SnappAuction.sol#L120-L125

where as, in regular `placeOrder` the batch is updated as

https://github.com/gnosis/dex-contracts/blob/18b76664f0de6572a7998b1f06ea9537f6d2489b/contracts/SnappAuction.sol#L159-L165

### Questions

1. Do we need to update unreserved order batch index on during placement of reserved order? Is this intended to update the `auctionIndex`
2. Is there a reason why the second condition 
```js
auctions[auctionIndex].size == maxUnreservedOrderCount()
```
is missing from the other one? 
3. If question 2 results in "this is a mistake", can we do the following:

```js
    function updateAuctionIndex() private {
        if (
            auctionIndex == MAX_UINT ||
            auctions[auctionIndex].size == maxUnreservedOrderCount() ||
            block.timestamp > (auctions[auctionIndex].creationTimestamp + 3 minutes)
        ) {
            createNewPendingBatch();
        }
    }
```

**Comment by josojo** [comment]
1. Yes, it is intended to update the auctionIndex, as otherwise, the batch would not be final after 3 mins, as reserved accounts could still update their orders for this particular orderindex
2. Yes, we do not increase the order size of non-resevered accounts. Hence, checking auctions[auctionIndex].size would be pointless
