### ISSUE TITLE
[Test Suite] Large numbers incorrectly interpreted in `encodeOrder` 

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#116]
When passing values such as

```
const order = encodeOrder(1, 0, 1,   100000000000000009) --> shows 100000000000000020   for last value
const order = encodeOrder(1, 0, 1,  1000000000000000009) --> shows 1000000000000000000  for last value
const order = encodeOrder(1, 0, 1, 10000000000000000009) --> shows 10000000000000000000 for last value
```
into `encodeOrder` shown here, we get very weird output/misinterpreted values. 

https://github.com/gnosis/dex-contracts/blob/351fc720b04d9b04555ac33307bab5213176340e/test/snapp_utils.js#L62-L64

**Comment by fleupold** [comment]
The problem is that the datatype Number in js can only safely store up to 53 bits.

Check out the following commands in `truffle console`:
```sh
truffle(development)> 10000000000000000009
10000000000000000000
truffle(development)> const BN = require('bn.js')
truffle(development)> var b = new BN('10000000000000000009', 10)
truffle(development)> b.toString()
'10000000000000000009'
truffle(development)> b.toNumber()
Error: Number can only safely store up to 53 bits
```

We should therefore probably support the [BigNumber](https://github.com/indutny/bn.js/) type directly and use it to convert our amounts into bit representation when it's larger than 53 bits.
