### ISSUE TITLE
[EpochTokenLocker] Should not be able to withdraw in next batch

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-contracts#166]
Currently we allow to perform the withdraw in the batch following the one it was requested.

https://github.com/gnosis/dex-contracts/blob/a1482139baa56cec49be0101142c716fc78acd43/contracts/EpochTokenLocker.sol#L73

However, this would mean we could withdraw balance as soon as the first (and not necessarily the best) solution has been submitted. The best solution might reverse our already withdrawn balance and could thus render us with a negative balance (or cause a double spend).

**Comment by josojo** [comment]
> However, this would mean we could withdraw balance as soon as the first (and not necessarily the best) solution has been submitted.

You have to elaborate here. A solution submission is not changing the state index. It is only changed by time.

**Comment by fleupold** [comment]
Let's say I submit an order in batch *t*, which sells A for B and at the same time submit a withdraw request for token B (any amount).
In batch *t+1* the first solution is submitted which fully executes my order.
I can now immediately claim my withdraw of token B (since *t < t+1*)
If, still in batch t+1, a better solution is submitted, which does not execute my order the balances get reverted.
This will either lead to me having a negative balance or cause a tx revert in which case my order could never be undone.

I think it should only be allowed to withdraw in batch *t+2*

**Comment by josojo** [comment]
Nice catch!

However, t+2 won't help two much. People could place withdraw request even further in the past for the buyToken. Then, once at some point in the future your order is filled and you get some balance, you could always withdraw it.

**Comment by josojo** [comment]
I think the best solution is that if someone gets a token credited via the addBalance function, we update the pendingWithdrawals to the current state index.

Of course this has bad side effects, as withdrawals might be delayed without a proper reason, but currently, I don't see a better solution.

**Comment by fleupold** [comment]
One idea would be to credit added balances to the pendingDeposits. This way they can only be withdrawn in the next batch. 

However, this would mean that we could temporarily have a negative main balance (e.g. if I traded A->B and B->C my first trade might have given me enough balance of B but only in the deposit part of my account, so when B gets deducted from my main balance for the 2nd trade it could go negative). From an external perspective, we should still be ok (it becomes harder to reason about internally though).

**Comment by fleupold** [comment]
> I think the best solution is that if someone gets a token credited via the addBalance function, we update the pendingWithdrawals to the current state index.

Would we revert this stateIndex increment when a new solution gets added? This could require to save a lot of extra data. If we didn't, I'd be afraid that someone could block my withdraw by submitting solutions that credit me small amounts of the token I want to withdraw in every batch. They would be overridden by more optimal solutions, but my balance would remain locked.

Not sure how real this attack is though.

**Comment by fleupold** [comment]
Another idea to avoid negative balances would be to introduce another pending flux in the BalanceState struct (pending income from auction), which is the amount credited from trades in the current batch. When reducing balance on a sell, we would first try to deduct from there and only if that value is 0 deduct from the regular balance.

With some more adjustments (adding another flux for pending deductions from auction) this could even implement the roll-back of previous solutions (by just overriding these values when a better solution arrives)

**Comment by josojo** [comment]
> If we didn't, I'd be afraid that someone could block my withdraw by submitting solutions that credit me small amounts of the token I want to withdraw in every batch. They would be overridden by more optimal solutions, but my balance would remain locked.

Yeah, I think this is not a real threat as you could just cancel your order and the attack would be stopped.

Yes, I would not undo the pendingWithdrawal state-change in this approach

**Comment by josojo** [comment]
>Another idea to avoid negative balances would be to introduce another pending flux in the BalanceState struct (pending income from auction), which is the amount credited from trades in the current batch. When reducing balance on a sell, we would first try to deduct from there and only if that value is 0 deduct from the regular balance.

good idea:

Let's investigate. In the current solution for roll-backs, I am storing the following data:
```
uint public previousSolutionBatchId;
    TradeData[] public previousSolutionTrades;
    uint[] public previousSolutionPrices;
    uint16[] public previousSolutionTokenIdForPrice;

    struct TradeData {
        address owner;
        uint volume;
        uint16 orderId;
    }
```
and in your solution, I would have to store:
```
    uint public previousSolutionBatchId;
    mapping( buyer  => mapping (buyTokenId => TradeDetails) trades
    TradeMetaData[] public previousSolutionTrades;

    struct TradeMetaData {
        address buyer;
        uint16 buyTokenId;
    }
    struct TradeDetails {
        address seller;
        uint volume;
       uint 16 sellTokenId
    }

function withdraw(address token) public {
        updateDepositsBalance(msg.sender, token); 
       require(trades[msg.sender][token].volume == 0)
     }
}

```

Hm.. the last proposal is a little bit more expensive, for the roll-back
However, it does not block withdrawals for an entire epoch.

I like both solutions.
I would go for the increasing pendingWithdrawal, as it is a little bit more gas efficient and less complexe to implement (at the current stage).

**Comment by koeppelmann** [comment]
I am undecided here. @josojo solution is maybe not the most elegant solution (because of the unintended side-effect) but it seems acceptable.
If a user has an open buy of a token order a malicious person could delay withdraws of that token until this order is canceled by submitting crappy solutions very early (that will get reverted) but that have this delay side-effect.
However - the costs are high to do this and it can be stoped by canceling the order - and most important - the negative effect is only a delay of withdrawal.
Overall this seems acceptable to me.

**Comment by josojo** [comment]
Updating the investigations:

**1. Solution:** delaying withdrawals:
Currently, we store for rollbacks:
```
    mapping (uint16 => uint128) public currentPrices;
    PreviousSolutionData public previousSolution;

    struct PreviousSolutionData {
        uint batchId;
        TradeData[] trades;
        uint16[] tokenIdsForPrice;
    }

    struct TradeData {
        address owner;
        uint128 volume;
        uint16 orderId;
    }
```
and the implementation would look like this:
```
// in submitSolution(){
postPoneWithdrawals()
}
    function postPoneWithdrawals(
        uint32 batchIndex
        uint16 token,
        address owner
    ) internal {
        if (balanceStates[msg.sender][token].pendingWithdraws.stateIndex<= currentBatchIndex)
            balanceStates[msg.sender][token].pendingWithdraws.stateIndex = currentBatchIndex
        }
    }
```

**2. Solution:** Pending SettlementFlux
In this suggested solution, we need to settle some trade amounts immediately, to not get negative balances and additionally store the trading influxes,
```
    mapping (uint16 => uint128) public currentPrices;
    PreviousSolutionData public previousSolution;
    mapping( buyer  => mapping (buyTokenId => Flux) tradeFlux


    struct PreviousSolutionData {
        uint batchId;
        TradeData[] trades;
        uint16[] tokenIdsForPrice;
    }

    struct TradeData {
        address owner;
        uint128 volume;
        uint16 orderId;
    }
    TradeMetaData[] public previousSolutionTrades;

    struct Flux {
        uint128  amount;
        uint16 batchId;
    }

```
with new logic in the withdraw function:
```
function withdraw(address token) public {
        updateBalance(msg.sender, token);  // processing the withdrawFlux if possible
      // do withdraw
     }
}
```
Overhead is definitively storing another uint128 and checking for each: getBalance one more pending flux

**Solution 3.** Pending Flux with organized applying in next solutionSubmisison call
>As a solution provider you could create a
SET OF PENDING BALANCE UPDATES
if you overwrite the solution you just have to create a new SET/list and delete/overwrite the previous one.
As a first set of submitting a solution, you are applying the previous updates from the last set.
Unfortunately, this would also require a user (at least if they wanted to make a withdrawal) to apply this set to make sure their balance is not already planned for use.

This is pretty similar to Felix's suggestion, just the applying of the solutions would be different.
Drawbacks are the increased storage compared to the first solution and that another solution has to be applied before a withdrawal can be processed.

---
Actually, if we would allow for negative balances in the epochTokenLock contract, then we do not need to store additional information for the solutions 3. Then we could just apply all the buyAmounts as pending fluxes or set of balance updates. Then, such a trading structure might be sufficient:

```
    uint public previousSolutionBatchId;
    mapping( buyer  => mapping (buyTokenId => TradeDetails) trades
    PreviousSolutionData public previousSolutionData;

    struct TradeMetaData {
        address buyer;
        uint16 buyTokenId;
    }
    struct PreviousSolutionData {
        uint batchId;
        TradeMetaData[] public previousSolutionTrades
        uint16[] tokenIdsForPrice;
    }
    struct TradeDetails {
        address seller;
        uint volume;
       uint 16 sellTokenId
    }
```

---
I would go for solution 1 as I would not expect users to request withdrawals before an trade and likely they want to save gas and consolidate their withdrawals anyways. 

Using solution3 might be a bigger issue for the user experience, as solutions might not be created in each batch.

Solution 2 seems to be the most expensive one gas wise but definitively has the best user experience. But since this might restrict the number of trades we can do per batch, I would not go for it.

**Comment by fleupold** [comment]
> [Option2] Overhead is definitively storing another uint128 and checking for each: getBalance one more pending flux

Don't we already store a volume for the trade? If we stored the buyVolume instead of the sellVolume we could for a withdraw check if there is a pending buyVolume at this token and only allow withdraw if the pendingVolume + withdraw amount is smaller than available balance?

**Comment by josojo** [comment]
> Don't we already store a volume for the trade? If we stored the buyVolume instead of the sellVolume we could for a withdraw check if there is a pending buyVolume at this token and only allow withdraw if the pendingVolume + withdraw amount is smaller than available balance?

For the reversion of trades we need to store the whole buyVolume. For the withdraws, we have to store the buyVolume - the sellVolume of the same token. 
E.g., if you have 0 ETH, you are buying 5 ETH, but sell 2 ETH for USDC, we have to store the buyVolume 5 ETH for reverting the trade, but for your procedure, we are interested in the number 3 ETH, as this is your "balance surplus"

that is what I mean by storing another uint128...

**Comment by fleupold** [comment]
> For the reversion of trades we need to store the whole buyVolume

Not sure what you mean by "whole" buyVolume. Right now we store one volume per executed order. We could sum all buyVolumes for a given token together on the fly and subtract that from the balance available to withdraw.

In your example, this would mean that we deduct 5ETH from the withdrawable balance, where really we should only deduct 3 ETH. Since this number is always an upper bound it would in the worst case (when buying and selling the same token in a batch) prevent you from withdrawing valid amounts (which solution1 would do in all cases where a token is touched).

But then I agree option1 is the simplest.

**Comment by josojo** [comment]
I wrote with Martin again: He said that we should implement the solution, which we are favoring.

@fleupold Is it okay if I am going with solution 1?
