### ISSUE TITLE
[Bug] EpochTokenLocker requestWithdraw should call withdraw

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#223]
In the current implementation, request withdraw can cancel an old request and thereby increase his balance for the previous auction and thereby manipulate prices...

**Comment by bh2smith** [comment]
So, I guess you are referring to the fact that these lines can potentially overwrite an existing request:

https://github.com/gnosis/dex-contracts/blob/acaec3f53d8a335f4ba3485814c04c0ffa02c68b/contracts/EpochTokenLocker.sol#L61-L64

Could you elaborate a bit on how overwriting a pending request can manipulate prices?

**Comment by fleupold** [comment]
Solvers will take existing "matured" withdraw requests into account by subtracting their value from the available balance (since by the time the settlement is submitted the amount may have been withdrawn). This may lead to some trades that could be executed limit price wise, to be unsatisfiable due to balance constraints.

However, if you had a way to "cancel" a valid withdraw in the current batch, you could run your solver with an increased balance of yours in mind and thus potentially execute more volume (and this generate a better solution than any benign solver). Just before submitting your solution you would cancel your valid withdraw to make sure the smart contract accepts your solution.

**Comment by josojo** [comment]
In order to solve this issue, we have to prevent immediate withdraws of any tokens that were credited in any last non-finalized auction settlement

 This means that either we have to 

- 1) withdraw old withdraw requests, so that there is no withdraw request in the system
- 2) prevent withdraws by another means: i.e, we could store another additional variable indicating whether the withdrawal would be allowed
```
(auctionId => token=> owner => wasCredited)
mapping( uint => address => address => bool) tokensWereCreditedInBatch
```


1) This solution has the downside that the solution submitter has to pay for the gas costs of the withdraw method. But I would suspect that this would not happen to often, it rather would be the exemption. An attacker could not easily exploit this without paying fee for his trades.

2) This solution has the downside that the solution provider has to pay for the gas cost of a new variable. This gas would only needed to be paid, in the same cases as when the withdraw would be required to be processed. (Otherwise, there would be no need to set these withdraw blockers) Hence the gas costs are cheaper, but compared to the first solution, this solution seems to be a little bit more complex.

Do you guys see better solutions?

**Comment by josojo** [comment]
Processing a withdraw would roughly cost 44k gas. If we have 25 orders to be settled and have to process 25withdraws additionally, we get an additional 1100k gas. That is quite a lot. 
Storing 25 new boolean variables might be significantly cheaper.

I talked with Martin and Stefan about it, and they would prefer the simplicity of doing the withdraws over introducing another variable.
 
I am currently still undecided...

**Comment by josojo** [comment]
Closed with PR
