### ISSUE TITLE
[BUG] Use rounding to get free OWL

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#292]
The executed sellAmount of an order is calculated from the executed buyAmount by a formula subject to rounding issues:
```
uint256(executedBuyAmount).mul(buyTokenPrice).div(feeDenominator - 1)
            .mul(feeDenominator).div(sellTokenPrice).toUint128();
```
These rounding issues can be abused to steal all OWL.

Here is an example ( exectuedSellAmount calculated without fee for simplicity):

![sideways](https://user-images.githubusercontent.com/11778116/68749174-1461b080-05fe-11ea-9b71-fbb9d741d5e8.png)

The prices of the fee token are chosen, such that the rounding error gets maximal. Effectively, in this example trade, we sell 1.9 * 10^20 OWL and buy only 10^20 OWL. That means that the difference of  0.9* 10^20 owl will be credited to the attacker.

------------

Proposed solution: 
(1) Enforce that the token conservation of the feeToken is at least 0.
=> This would ensure that no fee tokens can be stolen out of the contract

(2) Enforce that the token conservation of the feeToken is at least CollectedFees
=> This is the optimal requirement for making sure that such malicious ring trades are not included. But here, I am not sure whether we will always find valid solutions due to rounding

(3) Enforce that the token conservation of the feeToken is at least CollectedFees *x with x /in (0,1)
=> Middle way between (1) and (2). Most reasonable solution for me right now.
 
Anyways, I guess we need to calculate suddenly both on-chain: The collectedFees and the token conservation fo the feeToken.

**Comment by nlordell** [comment]
I think that token conservation of the fee token is already calculated (from what I understand it is `tokenConservation[0]` and used as the `totalFees` for calculating the objective value). It is just not checked as far as I can tell.

**Comment by josojo** [comment]
@nlordell 
yes, our assumption was that `tokenConservation[0]` would roughly equal `totalFees` and we used this assumption several times. These values would only equal roughly, as rounding errors occur.  But this example shows that the rounding errors can be huge and break many assumptions.

**Comment by bh2smith** [comment]
This can be easily avoided by simply rejecting orders trying to buy the fee token

**Comment by twalth3r** [comment]
> This can be easily avoided by simply rejecting orders trying to buy the fee token

Maybe this, plus requiring all executed sell amounts to be > 0 as suggested in https://github.com/gnosis/dex-contracts/issues/291, would do the job.

However, I feel like token prices differing that much in their order of magnitude may always cause unexpected effects...

**Comment by josojo** [comment]
> This can be easily avoided by simply rejecting orders trying to buy the fee token

I also like this idea more and more. It is much simpler than imposing than limits, as my solution (3), where we don't know how to choose them, such that we still find reasonable solutions all the time.

Also, it would safe us some gas.

**Comment by twalth3r** [comment]
Martin made another suggestion: Instead of requiring sell amounts to be > 0, we could also require them to be > 10**5 (or something similar) in order to make possible rounding errors smaller.

**Comment by bh2smith** [comment]
> I also like this idea more and more. It is much simpler than imposing than limits, as my solution (3), where we don't know how to choose them, such that we still find reasonable solutions all the time.

Note that this will require another complete change to all of our unit test examples (since all of them involve fulling orders back and forth between fee token and other tokens).

Perhaps we can go with @twalth3r's previous comment...

> Martin made another suggestion: Instead of requiring sell amounts to be > 0, we could also require them to be > 10**5 (or something similar) in order to make possible rounding errors smaller.


**Summary**

1. Do not allow orders buying the `feeToken`: 
_Would require completely rewriting all the test examples_!
2. `require(executedSellAmount > 10^5)` for all (max 25) touched orders: 
_Would not require any refactoring of test examples._

**Comment by josojo** [comment]
> require(executedSellAmount > 10^5) for all (max 25) touched orders:
Would not require any refactoring of test examples.

From a smart contract security point of view, I really dislike the solution. Estimating all the possible rounding errors is quite complex and error-prone. It would be much simpler to option (1), as then we can easily "see " that no attacks are possible.

But this is for sure also a business decision.

**Comment by bh2smith** [comment]
If we decide to go this route, we will have to adjust our test cases as follows (i.e. the red orders would be new)

![B2C6E608-3109-41CA-B656-960459C13B28_1_105_c](https://user-images.githubusercontent.com/11778116/68842614-eb592280-06c6-11ea-93da-1f4f2254d8cf.jpeg)

**Comment by bh2smith** [comment]
Lets give @koeppelmann the final decision on this one!

**Comment by bh2smith** [comment]
After a long discussion today (attendees: @josojo, @bh2smith, @koeppelmann, @nlordell and  @twalth3r), we have decided to go with the following options which minimize the amount of refactoring and appear to provide a sound level of security (i.e. that any fee token obtained via rounding error is strictly less than the amount of fees paid to generate it).

1. `require(amounts > 10^4)` where `amounts` is all executed (buy and sell) amounts and prices.
  => with this requirement, we are relatively sure, but not certain, that the rounding errors are smaller than the fees paid. But since in the worst case, only the fee mechanism is not working properly, this small uncertainty should be acceptable.
2. `require(tokenConservation[feeToken] > 0)` - which doesn't really have anything to do with this issue, but is surely a constraint that should be imposed.

**Comment by fleupold** [comment]
> `require(tokenConservation[feeToken] > 0)`

This was discussed on one of the PRs (https://github.com/gnosis/dex-contracts/pull/175#discussion_r320713485)
