### ISSUE TITLE
gas optimization: unlimited orders don't need to track "used amount"

### ISSUE THREAD

**Issue by koeppelmann** [gnosis/dex-contracts#419]
A magic number can be used to indicate that a order is meant to have unlimited capacity. In this case it would not be required at order execution to increase the used amount and thus safe half a storage update/slot.

This pattern is used e.g. for token allowance: 
https://etherscan.io/address/0xe41d2489571d322189246dafa5ebde1f4699f498#code check line 123

Code change required should only be:

```
     maxUnit = 2^128 - 1
    function updateRemainingOrder(address owner, uint256 orderId, uint128 executedAmount) private {
    	if orders[owner][orderId].priceNumerator < maxUnit
        	orders[owner][orderId].usedAmount = orders[owner][orderId].usedAmount.add(executedAmount).toUint128();
    }
```

**Comment by josojo** [comment]
Thanks for opening the issue!

Hm... maybe something like this would work:
```
maxUnit = 2^128 - 1
    function updateRemainingOrder(address owner, uint256 orderId, uint128 executedAmount) private {
    	if orders[owner][orderId].priceNumerator < maxUnit && orders[owner][orderId].priceDenominator < maxUnit
        	orders[owner][orderId].usedAmount = orders[owner][orderId].usedAmount.add(executedAmount).toUint128();
    }
```
As otherwise, it would be only possible for limit_prices > 1
And then we also need to update the reversionRemainingOrders.

The main reason why we have not yet implemented this was the missing incentive mechanism. As the gas is anyways paid by the solution submitter, I have no incentive to scale my order to indicate this feature, besides the fact that I am more likely to be included by a solver.

**Comment by fleupold** [comment]
@koeppelmann are you ok with not tackling this for our new release that we are planning for the end of the month? 
We talked about not focussing on gas optimizations for the MVP and this task feels like it would just save some gas. We can leave it on low-pri and see if we get to it. However, all changes will have to be re-reviewed as well.

**Comment by koeppelmann** [comment]
yeah, clearly not a requirement.
