### ISSUE TITLE
Unnecessary restrictive function requestWithdraw

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#424]
I've noticed another thing, it's impossible to requestFutureWithdraw if lastCreditBatchId is set and there is a pending withdraw for the active batch, this doesn't seem like a necessary restriction

--> Input from Adam

**Comment by fleupold** [comment]
Is this really unnecessary? We need to execute any pending withdraw before requesting a new one (since otherwise you could change the available balance you have in the batch currently being solved).
At the same time we cannot allow a withdraw to be executed if the person traded in the current batch (as they might claim proceeds that are subject to reverting).

Thus, I don't see an easy way of how we can allow this withdraw.

**Comment by josojo** [comment]
good point.
I didn't really think about it, I was just copy-pasting it.
