### ISSUE TITLE
Archive Snapp Contracts

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#522]
There will likely be several PRs relating to this change especially in [dex-services](https://github.com/gnosis/dex-services/) which should probably happen first.

The plan here is simple (in essence), we would like to tag the current master with something like `snapp-stable` and remove all contracts and tests related to the `Snapp`. This will dramatically reduce our travis build times and really slim down the overall code base.

**Comment by nlordell** [comment]
I'd say this should be a branch. This way, if we ever want to revisit, we can merge parts of master into this branch and slowly get it back to speed.

Ultimately there is almost no difference between a tag or a branch here (and we can also branch from the tag if needed, or create a tag on the tip of the branch and remove the branch later) so its more of a philosophical debate of whether this should be a tag or a branch. I think that since this is a parallel implementation of a next version of the dfusion protocol, it *feels* more like it should be on a branch.

Like I said though, it doesn't really matter and just wanted to voice my 0.0001% preference for a branch.

**Comment by koeppelmann** [comment]
I have no opinions about branch or not.
But one of the most urgent things related to this is to fix the https://github.com/gnosis/dex-contracts/blob/master/README.md which still points under Documentation to this ancient piece: https://github.com/gnosis/dex-research/blob/master/dFusion/dFusion.rst
