### ISSUE TITLE
Order Collection Parameters

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-contracts#56]
As we know, there are several different types of different orders that can be placed in a batch auction.

Categories (Market vs Limit)
Types (Buy, Sell & Double sided)

The question here for @fleupold @twalth3r and @josojo is which types we would like to accept and how will we do this?

Assuming we only handle Limit orders (Buy, Sell & Double Sided), it should suffice to use the following:

```js
function submitLimitOrder(
    buyToken: uint8,
    sellToken: uint8,
    maxSellAmount: uint128,
    maxBuyAmount: uint128,
    priceBuyToken: uint128,
    priceSellToken: uint128
)
```
Notice that specifying a positive integer for both sell and buy amount would constitute a **double-sided order**, whereas setting one or the other to zero would uniquely define the order as a **sell** or **buy** order respectively (i.e. maxBuyAmount = 0, could be interpreted as a Sell order and maxSellAmount = 0 interpreted as a Buy order). This could be interpreted as somewhat misleading (since the 0's would actually represent a value of infinity), but this should cover all possible cases of limit order definitions.

**Comment by josojo** [comment]
Only buy limit orders are enough for the start

**Comment by fleupold** [comment]
For the snark prototype we built at the end of last year we used only sell orders. Therefore, if it doesn't matter whether we use buy **or** sell orders in the beginning, we might as well use sell orders.

**Comment by bh2smith** [comment]
Ok then. So I will likely do something like this:

```js
function placeSellOrder(
    buyToken: uint8,
    sellToken: uint8,
    maxSellAmount: uint128,
    priceBuyToken: uint128,
    priceSellToken: uint128
)
```

If everyone agrees. 

Just note that the first suggestion with one additional parameter generalizes to all types of orders, so we will want to keep it in mind for the future.

**Comment by fleupold** [comment]
Is there a way to express orders with just two uint128?

For the snarks, we assumed that one order would fit into a single field element (253 bits). There was a longer discussion on how to encode data in https://github.com/gnosis/dex-zksnarks/issues/14

The codec used for the snark POC can be found here: https://github.com/gnosis/dex-zksnarks/blob/master/pepper/apps/parsing.h

For 30 Tokens and 1000 accounts an order would be encoded as:
- account: 10bit
- buyToken: 5bit
- sellToken: 5bit
- buyAmount: 100bit
- sellAmount: 100bit

I'm not sure if we want to have each of these fields be a separate argument or if the smart contract  wants to take a single 256bit value and assume the client encodes the ingredients correctly. 

What are your thoughts? It could save gas on call-data and the event payload size since we'd use only 256bits instead of >300bits per order.

If we take the arguments one by one, I'd suggest we check each value for overflow (e.g. sellToken <= 30).

**Comment by josojo** [comment]
So long term, we definitively only want to have it as brief as possible: 256 bytes order information + signatures bytes. Then we need to do the bytes operation etc.

But since we decided that we want to go with the easiest solution ( order submission by owner of order etc), I am perfectly fine with Bens solution. The good thing is that this, later on, can easily be refactored, its just the hashing + smart contract.

Overall, I really don't know how much we should keep simple and how much we should build correct right from the start...

**Comment by twalth3r** [comment]
The current encoding as written by @fleupold is particularly suited for limit sell orders.
`sellAmount` is an upper limit and `buyAmount` is interpreted as lower limit in case the entire `sellAmount` is used (which implicitly encodes the limit price).
If we want to use buy orders at some point, `buyAmount` would need to be an upper limit and `sellAmount` another upper limit for the case that the entire `buyAmount` is used.
This difference could probably also be encoded with another bit or two though...

**Comment by twalth3r** [comment]
One order type that can not be expressed with only a `buyAmount` and `sellAmount` parameter would be the following:
```
Spend at most <sellAmount> sellTokens to buy at most <buyAmount> buyTokens
if the price per unit of buyToken (measured in units of sellToken) <= limitPrice.
```
Not sure if want to have this order type at some point. Might make sense in some use cases and can already be handled by the solver.

**Comment by bh2smith** [comment]
After some some discussion, the current plan is to go with the following:

```js
    function placeSellOrder(
        uint8 buyToken,
        uint8 sellToken,
        uint128 maxSellAmount,
        uint128 minBuyAmount
    ) public onlyRegistered() {

    // require that buy and sell amount don't use more than 100 bits
    // crop the buy and sell amounts then hash the packed form something like
    // encodeFlux(accountId, buyToken, sellToken, cropped(maxSell), cropped(minBuy))
}
```

This is partially due to the fact that the accountId is determined by `msg.sender` from within the contract and would make it complicated pass a fully packed `bytes32` representation of the order data at this point (since it needs to be tampered with anyway).

Furthermore, this "contract optimization" can be taken care of on a second pass (once the minimum functionality is implemented). Of course this will be necessary once the contract accepts batch orders on submitted on behalf of other users and more compressed order representation will be required.

**Comment by fleupold** [comment]
It also resembles the same strategy we have been using so far for accepting deposits and withdraws.
