### ISSUE TITLE
Investigate the gas behaviour for getEncodedUsersPaginated

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-contracts#577]
The gas costs for getEncodedUsersPaginated seem to be depended on the orderbook size. 

This was not expected. Can someone investigate the gas consumption based on the orders in the orderbook?

More background:
https://docs.google.com/document/d/1o96yYSl5s78pOzUEqrw8_hDlBQbKu6qpUJ3rXLLD8vc/edit

**Comment by fleupold** [comment]
Here is the order placement tx from which on we were running out of gas: https://etherscan.io/tx/0xf0a215bdc9197589004c946e7989c09dfc434ad8012e65b05f37217091ab860f#eventlog

The user 0xeb13c6ff42f1307c026a7f6e2c97068658d9aea6 was putting in 2 orders every 5 minutes. At the point of failure they had 378 orders in the system.

We were querying 3 pages and were failing on the very last page (https://logs.gnosisdev.com/goto/411f6aae00157cc0a00e31617c280a79).

I replayed the eth_rpc calls in trace mode, e.g.

```
curl -H "Content-Type: application/json" -X POST https://node.mainnet.gnosisdev.com -d '{"jsonrpc":"2.0","method":"trace_call","params":[{"data":"0x95466a46000000000000000000000000eb13c6ff42f1307c026a7f6e2c97068658d9aea6000000000000000000000000000000000000000000000000000000000000002100000000000000000000000000000000000000000000000000000000000003e8","to":"0x6f400810b62df8e13fded51be75ff5393eaa841f"}, ["trace"], "latest"],"id":70457}' > t[D[D[D[Drace.json
```
which allowed me to plot the remaining gas at each library call (nextUser, tokenAddressLookup). It also showed that we started with roughly 500M gas in the request.

Page 2 contained 58 users and queried 1k orders. Their gas consumption was **well within the limit** looked like this:

<img width="587" alt="Screen Shot 2020-03-06 at 17 06 23" src="https://user-images.githubusercontent.com/1200333/76100438-ecdb8d00-5fcc-11ea-9127-95e930fb37a5.png">

Page 3 contained 68 users and queried only 740 orders before **running out of gas**. Their burn down chart looks like this:

<img width="583" alt="Screen Shot 2020-03-06 at 17 09 43" src="https://user-images.githubusercontent.com/1200333/76100672-58255f00-5fcd-11ea-9f86-d2aa7da7a7ee.png">

When increasing the offset of the last page by the number of orders that have been placed between the last queriable order book (5:00 UTC) and now (27 orders) I was able to run the query without running out of gas (this time querying 80 users and 766 orders) but getting close:

<img width="577" alt="Screen Shot 2020-03-06 at 17 31 24" src="https://user-images.githubusercontent.com/1200333/76102465-56a96600-5fd0-11ea-9f23-16913ade55eb.png">

We can see the gas consumption is increasing quadratically and then "relaxing" at some points in the graph. These relaxations tend to happen when we iterate to the next user (identified by checking calls to IterableAppendOnlySet.next). 

My assumption is that in those cases some memory is freed and thus additional memory becomes cheaper again (memory cost grows quadratically).

### Evaluating the fix

I reran the same analysis on the now reduced page size of 500 (6 users, 500 orders):

<img width="586" alt="Screen Shot 2020-03-06 at 17 25 52" src="https://user-images.githubusercontent.com/1200333/76102809-de8f7000-5fd0-11ea-8e41-6c656342752c.png">

and 74 users 290 orders:

<img width="582" alt="Screen Shot 2020-03-06 at 17 35 36" src="https://user-images.githubusercontent.com/1200333/76102850-ebac5f00-5fd0-11ea-940e-ff26bfdf9afa.png">

In order to really evaluate our worst case scenario, we would have to rerun the query with 500 orders on the same user (and potentially pending deposit and withdraws). Unfortunately, ganache crashes in such extreme cases thus this is not easily possible.

The graphs can be found [here](https://docs.google.com/spreadsheets/d/1gQ9RGpUmMLy1ZA4VOp7CNyrD7TTAB52cx1bPf3URNSQ/edit#gid=1091098559) and I'm attaching the traces:

[OutOfGas.zip](https://github.com/gnosis/dex-contracts/files/4299344/OutOfGas.zip)

**Comment by fleupold** [comment]
By quadratically extrapolating the values from the first "500 order graph", I believe a single user would use roughly 31M gas when having placed 500 orders:

```
f(x) = k * x^2
f(400) = 20M = k * 400^2
k = 125

=> f(500) = 125 * 500**2 = 31.25M
```

Thus, using a page size of 500 should be fine. On the other hand, we are not yet using the largest possible gas limit for our view calls. If we can figure out how to make parity allow more than 500M in gas limit we could re-increase the page size.

**Comment by fleupold** [comment]
Here is the line that I believe limits the maximum gas amount to 500M for view funtions: https://github.com/OpenEthereum/open-ethereum/blob/3ccfe735aa579f89a1f8de192a7625084a6f530f/rpc/src/v1/helpers/fake_sign.rs#L25

**Comment by e00E** [comment]
We talked about this in a meeting. One way to improve this would be that when
getEncodedUsersPaginated calls getEncodedUserOrdersPaginated it wouldn't have to copy the orders from the user into the final array to avoid the `elements = elements.concat...`. Could pass if elements as "mutable reference" if that is possible or internally use a much smaller page size here instead of forwarding the total page size.

**Comment by fleupold** [comment]
I spoke with @cag about this and while it's theoretically possible to concatenate arrays in place using assembly, it is somewhat unsafe as it might override existing memory. The best way would probably be to allocate a large enough slice (we now the upper bound from our page size), fill it until no more orders are in the system or the page is filled and then reduce the size element (first u256 of allocated memory) to the potentially shorter length.

**Comment by fleupold** [comment]
To summarise, we are running into an "accidentally quadratic" allocation inefficiency by not extending the bytes array in place. Therefore if a single user has 500 orders we allocate arrays of size 1, 2, ... 500. The same is true if there is 500 users with each one order. The following python code simulates the "inefficient allocation":


```python
sum = 0

def inefficient_alloc(count):
  global sum
  sum += count

inner = 23
outer = 23

for i in range(outer):
  for j in range(inner):
    inefficient_alloc(j)
  inefficient_alloc(i * inner)

print sum
```

The "sweet spot" is having an "even" distribution between users and orders (e.g 23 user with ~23 orders each), leading to <12k items allocated, whereas the extremes with 500 orders and 1 users or vice versa leads to >100k items allocated.

@cag also noted that we can potentially "patch" our view functions if we were to depend on geth as a node by using their contract override feature (https://geth.ethereum.org/docs/rpc/ns-eth#override-example)

**Comment by bh2smith** [comment]
This looks as if it has been finished? Does #623 close this issue?

**Comment by nlordell** [comment]
Yes, I believe this is closed, as we have the new viewer methods that are more gas efficient and should be able to page through arbitrarily sized orderbooks.
