### ISSUE TITLE
[Feature] Order Cancellations

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-contracts#86]
The purpose of this issue is to discuss, how order cancellation should work. Cancellation is definitely needed for rollover orders (in case they are no longer wanted). This issue is therefore somewhat dependant on #85.

However, it would also be nice to be able to cancel one-off orders in the current batch assuming the batch hasn't been closed yet.

Subscribing @bh2smith @twalth3r @josojo

**Comment by fleupold** [comment]
## Order Cancellation Hash

One idea would be to collect cancellations in the same way as orders. A cancellation would consist of an `accountId` (to verify one can only cancel ones own orders) and a `slotIndex` pointing at the index of the order inside the batch that should be cancelled.

```
function cancelOrder(uint16 slotIndex) {
  uint16 accountId = publicKeyToAccountMap(msg.sender);
  bytes32 nextCancellationHash = sha256(
    abi.encode(auctions[auctionIndex].cancellationHash, accountId, slotIndex)
  );
  auctions[auctionIndex].cancellationHash = nextCancellationHash;
  emit OrderCancellation(auctionIndex, accountId, slotId);
}
```

Note, that an order cancellation doesn't effectively increase the number of available slots left in the batch. It should more be thought of as overriding the current order with 0s.

When computing the list of "valid" orders the solver checks for each order if there was a cancellation for this slot index by the same account that has authored the original order. If so, the order is replaced with all 0s.
The "merged" order bit representation (taking all valid cancellations into account) is hashed and submitted as part of the full solution on chain.

```
function applyAuction(
        uint slot,
        bytes32 _currStateRoot,
        bytes32 _newStateRoot,
=>      bytes32 mergedOrderHash,
        bytes memory pricesAndVolumes,
)
```

The correct computation of this merged order hash can be challenged like any other aspect of the solution.

### Discussion

Challenging the correct composition of the merged order hash is quite expensive. If done on-chain it would cost ~10M gas for 1k orders and would thus have to be broken up into two txs.

**Comment by bh2smith** [comment]
Function described above will also want to have `uint auctionIndex` in its signature (as this appears to have come from nowhere. That is,

```js
function cancelOrder(uint16 slotIndex, uint auctionIndex) { ... }
```

Driver will need to ensure that `accountId` is the "rightful" owner of the order placed at `auctionIndex, slotIndex` (since the contract cannot know this). 

**Question**: If an invalid cancelation (i.e. one with incorrect `accountId`) was submitted to the contract. Would be analogous to how invalid withdrawals are treated?

I would assume the above proposed `mergedOrderHash` would be something like

```python
def mergedOrderHash(orders: List[Order], cancelations: List[Tuple[int, int]]):
    for slot, account_id in cancelations:
        if orders[slot].account_id == account_id:
            orders[slot] = NullOrder()
            
    return reduce(hash_fn, orders)
```
my concern with this is that the contract is incapable of verifying this `mergedOrderHash`. Hopefully this is not necessary. I suppose this information is just necessary to verify that the cancelations considered were as expected?
